### ISSUE TITLE
Support for Markdown

### ISSUE THREAD

**Issue by SethCalkins** [kelyvin/jsonresume-theme-caffeine#3]
I'm looking for a way in passing markdown (specifically bold words) from JSON file..is this something you can help with?

**Comment by kelyvin** [comment]
Hi SethCalkins, I think this is something I can help with, however, it will be very specific to this resume theme. 

I created this repo to provide a proper build environment for theme development, and eventually providing my own custom theme (the date for that is tbd). This custom theme should be able to support what you're asking. Stay tuned!

**Comment by SethCalkins** [comment]
Thanks so much ... I definitely appreciate it!
